apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    author: qi.xu
  name: record-ms-deployment
  labels:
    app: record-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: record-ms
  template:
    metadata:
      labels:
        app: record-ms
    spec:
      containers:
        - name: record-ms
          image: xbobo/investment_calculator:record_1.6
          ports:
            - containerPort: 9094
          env:
            - name: IC_GRPC_ADDR
              value: 'ic-grpc-service:9092'

---
apiVersion: v1
kind: Service
metadata:
  name: record-ms-service
spec:
  selector:
    app: record-ms
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
